use_frameworks!

target 'MarvelApiWrapper_Example' do
  pod 'MarvelApiWrapper', :path => '../'

  target 'MarvelApiWrapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
