# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.1
os: osx
language: swift
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - gem install xcpretty -N
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 8' -workspace Example/MarvelApiWrapper.xcworkspace -scheme MarvelApiWrapper-Example ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
